// ── BADGES.JS — Images réelles depuis faluche.info ───────────────────────────
const BASE = 'https://faluche.info/wp-content/uploads/2020/01/';

const BADGE_SVG = {
  // Circulaires
  caducee_medecine:   '<img src="' + BASE + 'insigne-medecine.jpg">',
  caducee_mercure:    '<img src="' + BASE + 'insigne-caducee-commerce.jpg">',
  caducee_pharmacie:  '<img src="' + BASE + 'caducee-pharmacie-1.jpg">',
  glaive_balance:     '<img src="' + BASE + 'insigne-balance.jpg">',
  ankh:               '<img src="' + BASE + 'insigne-croix-de-hank.jpg">',
  molaire:            '<img src="' + BASE + 'insigne-molaire.jpg">',
  etoile_foudre:      '<img src="' + BASE + 'insigne-etoile-et-foudre.jpg">',
  tete_de_mort:       '<img src="' + BASE + 'insigne-tete-mort-croise-femurs.jpg">',
  chouette_bicephale: '<img src="' + BASE + 'insigne-chouette-2-faces.jpg">',
  spheroide:          '<img src="' + BASE + 'insigne-sphynx.jpg">',
  tete_cheval:        '<img src="' + BASE + 'insigne-tete-de-cheval.jpg">',
  parapluie:          '<img src="' + BASE + 'insigne-parapluie.jpg">',
  coq:                '<img src="' + BASE + 'insigne-coq.jpg">',
  casque_pericles:    '<img src="' + BASE + 'insigne-pericles.jpg">',
  livre_plume:        '<img src="' + BASE + 'insigne-livre-ouvert-plume.jpg">',
  lyre:               '<img src="' + BASE + 'insigne-lyre.jpg">',
  grappe_raisin:      '<img src="' + BASE + 'insigne-grappe-raisin.jpg">',
  palette_pinceau:    '<img src="' + BASE + 'insigne-pallette.jpg">',
  equerre_compas:     '<img src="' + BASE + 'insigne-equerre-et-compas.jpg">',
  masque_comedie:     '<img src="' + BASE + 'insigne-masque.jpg">',
  grenouille:         '<img src="' + BASE + 'insigne-grenouille.jpg">',
  ciseaux:            '<img src="' + BASE + 'insigne-cisseau.jpg">',
  infirmier:          '<img src="' + BASE + 'insigne-infirmier.jpg">',

  // Cursus
  etoile_or:          '<img src="' + BASE + 'insigne-etoile-or-B.jpg">',
  etoile_argent:      '<img src="' + BASE + 'insigne-etoile-argent-B.jpg">',
  palme_major:        '<img src="' + BASE + 'insigne-palme-major.jpg">',
  palme_diplome:      '<img src="' + BASE + 'insigne-palme-diplome.jpg">',
  palme_sciences:     '<img src="' + BASE + 'insigne-palme-des-sciences.jpg">',
  tete_vache:         '<img src="' + BASE + 'insigne-tete-vache.jpg">',
  tete_mort_simple:   '<img src="' + BASE + 'insigne-tete-de-mort.jpg">',
  quille:             '<img src="' + BASE + 'insigne-quille.jpg">',

  // Insignes personnels
  chameau:            '<img src="' + BASE + 'chameau1.jpg">',
  cochon:             '<img src="' + BASE + 'cochon2.jpg">',
  pendu:              '<img src="' + BASE + 'insigne-pendue.jpg">',
  feuille_vigne:      '<img src="' + BASE + 'insigne-feuille-de-vigne.jpg">',
  epi_ble:            '<img src="' + BASE + 'insigne-epi-de-ble.jpg">',
  fer_cheval:         '<img src="' + BASE + 'insigne-fer-a-cheval.jpg">',
  fourchette:         '<img src="' + BASE + 'insigne-fourchette.jpg">',
  plume:              '<img src="' + BASE + 'insigne-plume.jpg">',
  nounours:           '<img src="' + BASE + 'insigne-nounours.jpg">',
  sphinx:             '<img src="' + BASE + 'insigne-sphynx.jpg">',
  abeille:            '<img src="' + BASE + 'insigne-abeille.jpg">',

  // Insignes partenaire
  epee:               '<img src="' + BASE + 'insigne-epee.jpg">',
  fleche:             '<img src="' + BASE + 'insigne-fleche.jpg">',
  lime:               '<img src="' + BASE + 'insigne-lime.jpg">',

  // Insignes GM
  bacchus:            '<img src="' + BASE + 'insigne-bacchus.jpg">',
  bouteille_bordeaux: '<img src="' + BASE + 'insigne-bouteille.jpg">',
  bouteille_champagne:'<img src="' + BASE + 'insigne-bouteille-champagne.jpg">',
  cle_sol:            '<img src="' + BASE + 'insigne-cle-de-sol-B.jpg">',
  cor_chasse:         '<img src="' + BASE + 'insigne-cor-de-chasse.jpg">',
  mammouth:           '<img src="' + BASE + 'insigne-mammouth.gif">',
  pachyderme:         '<img src="' + BASE + 'insigne-pachyderme.gif">',
  poule:              '<img src="' + BASE + 'insigne-poule-1.jpg">',
  singe:              '<img src="' + BASE + 'insigne-singe-1.jpg">',
  hache:              '<img src="' + BASE + 'insigne-hache.jpg">',
  tortue:             '<img src="' + BASE + 'insigne-tortue.jpg">',
  volant:             '<img src="' + BASE + 'insigne-volant.jpg">',
  parapluie_ouvert:   '<img src="' + BASE + 'insigne-parapluie.jpg">',
  sou_troue:          '<img src="' + BASE + 'insigne-sou-troue.jpg">',
  faux:               '<img src="' + BASE + 'insigne-faux.jpg">',
};

// Map question id → badge key (inchangé)
const BADGE_MAP = {
  'cv3': 'caducee_medecine',
  'cv4': 'spheroide',
  'cv5': 'ciseaux',
  'cv7': 'caducee_pharmacie',
  'cv8': 'chouette_bicephale',
  'cv9': 'ankh',
  'cv11':'tete_cheval',
  'cv16':'infirmier',
  'cv17':'caducee_mercure',
  'cv18':'tete_de_mort',
  'cs1': 'glaive_balance',
  'cs2': 'etoile_foudre',
  'cs4': 'caducee_mercure',
  'cs5': 'livre_plume',
  'cs7': 'lyre',
  'cs8': 'grappe_raisin',
  'cs9': 'palme_sciences',
  'cs11':'parapluie',
  'cs13':'equerre_compas',
  'cs15':'chouette_bicephale',
  'cs16':'coq',
  'cs17':'sphinx',
  'cs21':'casque_pericles',
  'cs22':'grenouille',
  'cs24':'masque_comedie',
  'cs28':'palette_pinceau',
  'cu1': 'etoile_or',
  'cu2': 'etoile_argent',
  'cu5': 'palme_diplome',
  'cu6': 'tete_vache',
  'cu7': 'tete_mort_simple',
  'cu11':'quille',
  'cu12':'abeille',
  'ip1': 'chameau',
  'ip2': 'chameau',
  'ip5': 'cochon',
  'ip7': 'pendu',
  'ip9': 'bacchus',
  'ip11':'epi_ble',
  'ip13':'epi_ble',
  'ip14':'feuille_vigne',
  'ip17':'nounours',
  'ip15':'sphinx',
  'ip18':'abeille',
  'part1':'epee',
  'part2':'epee',
  'gm1': 'abeille',
  'gm3': 'bacchus',
  'gm5': 'bouteille_bordeaux',
  'gm7': 'bouteille_champagne',
  'gm9': 'coq',
  'gm11':'cor_chasse',
  'gm15':'fourchette',
  'gm17':'pachyderme',
  'gm18':'parapluie_ouvert',
  'gm19':'poule',
  'gm21':'singe',
  'gm23':'sou_troue',
  'gm25':'tortue',
  'gm26':'volant',
  'gm27':'cle_sol',
  'gm28':'mammouth',
  'v1':  'faux',
  'v4':  'grenouille',
  'v5':  'grenouille',
  'v6':  'tortue',
  'v7':  'tortue',
};
