const ALL_QUESTIONS = [
  // ══ HISTOIRE & ORIGINES ══
  { id:"h1", q:"[NATIONAL] En quelle année et où la faluche a-t-elle été officialisée ?", a:"Le 20 décembre 1888 au Théâtre Beaumarchais à Paris, à l'initiative de l'Association Générale des étudiants de Paris.", cat:"Histoire", src:"NATIONAL" },
  { id:"h2", q:"[NATIONAL] Quel événement a inspiré la création de la faluche ?", a:"Le retour d'une délégation d'étudiants français aux Fêtes du Huitième Centenaire de l'Université de Bologne, en juin 1888.", cat:"Histoire", src:"NATIONAL" },
  { id:"h3", q:"[NATIONAL] En quelle année a débuté la réunification nationale de la Faluche, et dans quelle ville ?", a:"En 1986 à Reims.", cat:"Histoire", src:"NATIONAL" },
  { id:"h4", q:"[IPP] En quelle année le code IPP a-t-il été créé et par qui ?", a:"En 2017, par les faluchard·e·s Ingénieurs Puceaux Parisiens (IPP), comme un « fork » du code national.", cat:"Histoire", src:"IPP" },
  { id:"h5", q:"[IPP] Qu'est-ce que la Croix IPP et quand a-t-elle été créée ?", a:"La Croix IPP (Ingénieurs Puceaux Parisiens) a été créée en l'an 5 de la fusion des croix d'École de Paris et d'Île-de-France. C'est le symbole de l'union des élèves ingénieurs de cette région.", cat:"Histoire", src:"IPP" },
  { id:"h6", q:"[NATIONAL] Quelles modifications majeures ont été apportées lors du 137e anniversaire ?", a:"Retrait de l'insigne chouette ; modification de l'Article XVII ; remplacement de « navet » par « sodomie » ; ajout de l'edelweiss pour la Savoie ; précisions sur ciseaux, épée/pensée, feuille de vigne ; refonte du circulaire école d'ingénieurs en « bleu roy et noir ».", cat:"Histoire", src:"NATIONAL" },

  // ══ RÈGLES GÉNÉRALES ══
  { id:"r1", q:"[NATIONAL] Devant qui peut-on retirer sa faluche ?", a:"Uniquement devant un recteur. On ne l'enlève pas devant un professeur.", cat:"Règles", src:"NATIONAL" },
  { id:"r2", q:"[NATIONAL] La faluche se réclame-t-elle d'une appartenance politique, religieuse ou syndicale ?", a:"Non, aucune appartenance politique, religieuse ou syndicale.", cat:"Règles", src:"NATIONAL" },
  { id:"r3", q:"[IPP] De quoi la faluche ne se réclame-t-elle pas selon le code IPP (liste complète) ?", a:"D'aucune appartenance politique, religieuse, syndicale, géopolitique, science politique, adiabatique ni Stanley Cubrique.", cat:"Règles", src:"IPP" },
  { id:"r4", q:"[IPP] Que dit l'article III-bis du code IPP ?", a:"Un tableau des prix : Tomate cerise (500g) = 2,5 €.", cat:"Règles", src:"IPP" },
  { id:"r5", q:"[IPP] Que dit l'article XLII du code IPP ?", a:"Tout·e faluchard·e ingénieur irrespectueux·se envers ses croix sera privé·e de nouba à la pistoche. Si insuffisant, obligation de boire du rhum-tomate.", cat:"Règles", src:"IPP" },
  { id:"r6", q:"[IPP] Comment déterminer l'orientation politique d'une croix selon l'article II-bis ?", a:"Ruban de croix porté à gauche = croix de gauche ; ruban de croix porté à droite = croix de droite.", cat:"Règles", src:"IPP" },
  { id:"r7", q:"[IPP] Que dit le code IPP sur les adoptions IF ?", a:"Non.", cat:"Règles", src:"IPP" },
  { id:"r8", q:"[NATIONAL] Que doit faire quelqu'un qui met une faluche ne lui appartenant pas ?", a:"Subir une épreuve choisie par le propriétaire de la faluche.", cat:"Règles", src:"NATIONAL" },
  { id:"r9", q:"[NATIONAL] Que doit faire quelqu'un qui demande à voir l'intérieur (potager) d'une faluche ?", a:"Passer par les armes suivant les goûts des protagonistes, qui choisissent le lieu, le jour et l'heure.", cat:"Règles", src:"NATIONAL" },

  // ══ STRUCTURE ══
  { id:"s1", q:"[NATIONAL/IPP] Quelles sont les deux grandes parties de la faluche ?", a:"1. Le ruban circulaire avec ses emblèmes (cursus estudiantin). 2. Le velours noir avec ses rubans et insignes.", cat:"Structure", src:"BOTH" },
  { id:"s2", q:"[IPP] De quoi le circulaire peut-il être fait selon le code IPP (matériaux autorisés et interdit) ?", a:"Peut être en bois ou en plexiglass. Le métal est interdit, réservé à la fabrication de canettes.", cat:"Structure", src:"IPP" },
  { id:"s3", q:"[IPP] Quelle philosophie le code IPP associe-t-il au velours vs satin ?", a:"Velours = filières bonne ambiance. Satin = relous, pleureurs et drama kings. Lin ou coton = filières inconnues (la chance du débutant).", cat:"Structure", src:"IPP" },

  // ══ CIRCULAIRES VELOURS ══
  { id:"cv1", q:"[NATIONAL] Circulaire complet : Chirurgie dentaire", a:"Molaire sur Velours violet pour Chirurgie dentaire", cat:"Circulaire velours", src:"NATIONAL" },
  { id:"cv2", q:"[NATIONAL] Circulaire complet : Études courtes de santé", a:"Squelette sur Velours blanc pour Études courtes de santé", cat:"Circulaire velours", src:"NATIONAL" },
  { id:"cv3", q:"[NATIONAL] Circulaire complet : Médecine", a:"Caducée médecine sur Velours rouge pour Médecine", cat:"Circulaire velours", src:"NATIONAL" },
  { id:"cv4", q:"[NATIONAL] Circulaire complet : Ostéopathie", a:"Sphénoïde sur Velours bleu roy pour Ostéopathie", cat:"Circulaire velours", src:"NATIONAL" },
  { id:"cv5", q:"[NATIONAL] Circulaire complet : Paramédical", a:"Ciseaux sur Velours rose pour Paramédical", cat:"Circulaire velours", src:"NATIONAL" },
  { id:"cv6", q:"[IPP] Comment le code IPP nomme-t-il le circulaire du paramédical ?", a:"Satin rose trompeur (au lieu de velours rose dans le national).", cat:"Circulaire velours", src:"IPP" },
  { id:"cv7", q:"[NATIONAL] Circulaire complet : Pharmacie / préparateurs en pharmacie", a:"Caducée de pharmacie / Mortier et pilon sur Velours vert pour Pharmacie / Préparateurs en pharmacie", cat:"Circulaire velours", src:"NATIONAL" },
  { id:"cv8", q:"[NATIONAL] Circulaire complet : Classes préparatoires santé", a:"Chouette bicéphale sur Velours marron pour Classes préparatoires santé", cat:"Circulaire velours", src:"NATIONAL" },
  { id:"cv9", q:"[NATIONAL] Circulaire complet : Sage-Femme", a:"Croix d'Ânkh sur Velours fuchsia pour Sage-Femme", cat:"Circulaire velours", src:"NATIONAL" },
  { id:"cv10", q:"[IPP] Comment le code IPP désigne-t-il le circulaire de Sage-Femme ?", a:"Sage-Femme : « Meuf d'Antoine ». Sage-Femme PO : Satin Fuchsia.", cat:"Circulaire velours", src:"IPP" },
  { id:"cv11", q:"[NATIONAL] Circulaire complet : Vétérinaire", a:"Tête de cheval sur Velours bordeaux pour Vétérinaire", cat:"Circulaire velours", src:"NATIONAL" },
  { id:"cv12", q:"[IPP] Comment le code IPP nomme-t-il la pharmacie ?", a:"Velours vert gelée.", cat:"Circulaire velours", src:"IPP" },
  { id:"cv13", q:"[IPP] Quelle filière le code IPP appelle « Ceux qui courent après la baballe » ?", a:"Les filières sportives — Satin vert foncé.", cat:"Circulaire velours", src:"IPP" },
  { id:"cv14", q:"[IPP] Quelle filière le code IPP appelle « Tout ce qui va te mener au McDo/Chômage » ?", a:"Lettres, langues, sciences humaines, sciences sociales — Satin jaune.", cat:"Circulaire velours", src:"IPP" },
  { id:"cv15", q:"[IPP] Comment le code IPP désigne-t-il les Sciences ?", a:"« Chiences » — Satin violet.", cat:"Circulaire velours", src:"IPP" },
  { id:"cv16", q:"[NATIONAL] Circulaire complet : Infirmier", a:"Caducée infirmier sur Velours rose pour Infirmier (paramédical)", cat:"Circulaire velours", src:"NATIONAL" },
  { id:"cv17", q:"[NATIONAL] Circulaire complet : Kinésithérapie", a:"Caducée de Mercure sur Velours rose pour Kinésithérapie (paramédical)", cat:"Circulaire velours", src:"NATIONAL" },
  { id:"cv18", q:"[NATIONAL] Circulaire complet : PASS", a:"Tête de mort sur fémurs croisés sur Velours couleur filière santé choisie pour PASS", cat:"Circulaire velours", src:"NATIONAL" },

  // ══ CIRCULAIRES SATIN ══
  { id:"cs1", q:"[NATIONAL] Circulaire complet : Droit", a:"Glaive et balance sur Satin rouge pour Droit", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs2", q:"[NATIONAL] Circulaire complet : Écoles d'ingénieurs", a:"Étoile et foudre sur Satin bleu roy et noir pour Écoles d'ingénieurs", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs3", q:"[IPP] Comment le code IPP nomme l'insigne des écoles d'ingénieurs ?", a:"« Étoile et foutre » (le nom de l'école peut être indiqué).", cat:"Circulaire satin", src:"IPP" },
  { id:"cs4", q:"[NATIONAL] Circulaire complet : Écoles de commerce, gestion, communication et journalisme", a:"Caducée de Mercure sur Satin rouge et vert pour Écoles de commerce, gestion, communication et journalisme", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs5", q:"[NATIONAL] Circulaire complet : Lettres, langues, sciences humaines, sciences sociales", a:"Livre ouvert et plume sur Satin jaune pour Lettres, langues, sciences humaines, sciences sociales", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs6", q:"[NATIONAL] Circulaire complet : MEEF", a:"Plume sur Satin gris pour MEEF", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs7", q:"[NATIONAL] Circulaire complet : Musique, musicologie", a:"Lyre sur Satin argenté pour Musique, musicologie", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs8", q:"[NATIONAL] Circulaire complet : Œnologie", a:"Grappe de raisin sur Satin saumon pour Œnologie", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs9", q:"[NATIONAL] Circulaire complet : Sciences", a:"Palmes croisées de chêne et de laurier avec initiales de la discipline sur Satin violet pour Sciences", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs10", q:"[NATIONAL] Circulaire complet : Sciences économiques, gestion et IAE", a:"Caducée de Mercure / Lettres IAE sur Satin orange pour Sciences économiques, gestion et IAE", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs11", q:"[NATIONAL] Circulaire complet : Sciences politiques", a:"Parapluie sur Satin rouge et bleu pour Sciences politiques", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs12", q:"[NATIONAL] Circulaire complet : Théologie", a:"Emblème de la religion correspondante ou lettres TH sur Satin blanc et rouge pour Théologie", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs13", q:"[NATIONAL] Circulaire complet : Architecture", a:"Équerre et compas sur Satin bleu pour Architecture", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs14", q:"[NATIONAL] Circulaire complet : BUT, DUT, BTS, Bachelor (au RNCP)", a:"Lettres BUT / DUT / BTS / β (Bachelor) sur Satin blanc pour BUT, DUT, BTS, Bachelor (au RNCP)", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs15", q:"[NATIONAL] Circulaire complet : Classes préparatoires (hors santé)", a:"Chouette bicéphale sur Satin marron pour Classes préparatoires (hors santé)", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs16", q:"[NATIONAL] Circulaire complet : Filières sportives", a:"Coq sur Satin vert foncé pour Filières sportives", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs17", q:"[NATIONAL] Circulaire complet : Histoire de l'art et archéologie", a:"Sphinx sur Satin jaune pour Histoire de l'art et archéologie", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs18", q:"[NATIONAL] Circulaire complet : Philosophie", a:"φ (phi) sur Satin jaune pour Philosophie", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs19", q:"[NATIONAL] Circulaire complet : Psychologie", a:"ψ (psi) sur Satin jaune pour Psychologie", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs20", q:"[NATIONAL] Circulaire complet : Géographie", a:"Globe sur Satin jaune pour Géographie", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs21", q:"[NATIONAL] Circulaire complet : Histoire", a:"Casque de Périclès sur Satin jaune pour Histoire", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs22", q:"[NATIONAL] Circulaire complet : Sociologie", a:"Grenouille sur Satin jaune pour Sociologie", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs23", q:"[NATIONAL] Circulaire complet : Administration Économique et Sociale (AES)", a:"Lettres « AES » sur Satin vert clair pour Administration Économique et Sociale (AES)", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs24", q:"[NATIONAL] Circulaire complet : Arts du spectacle", a:"Masque de comédie sur Satin bleu pour Arts du spectacle", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs25", q:"[NATIONAL] Circulaire complet : Communication", a:"Caducée de Mercure sur Satin couleurs de la filière de rattachement pour Communication", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs26", q:"[NATIONAL] Circulaire complet : Écoles nationales", a:"Lettres des initiales de l'école sur Satin couleurs du pays de l'école pour Écoles nationales", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs27", q:"[NATIONAL] Circulaire complet : DU", a:"Lettres « DU » sur Satin couleur de l'UFR de rattachement pour DU", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs28", q:"[NATIONAL] Circulaire complet : Beaux-arts et arts plastiques", a:"Palette et pinceau sur Satin bleu pour Beaux-arts et arts plastiques", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs29", q:"[IPP] Quelle filière le code IPP appelle MIASHS et quel insigne ?", a:"MIASHS — insigne : « MIASHS ».", cat:"Circulaire satin", src:"IPP" },

  // ══ CURSUS UNIVERSITAIRE ══
  { id:"cu1", q:"[NATIONAL] Que représente une étoile dorée sur le circulaire ?", a:"Une année d'études validée (se place en début d'année).", cat:"Cursus", src:"NATIONAL" },
  { id:"cu2", q:"[NATIONAL] Que représente une étoile argentée sur le circulaire ?", a:"Une année redoublée, 5/2 ou 7/2.", cat:"Cursus", src:"NATIONAL" },
  { id:"cu3", q:"[NATIONAL] Que signifie un zéro sur le circulaire ?", a:"Une année blanche, sabbatique ou de césure (pour éviter la confusion avec le redoublement).", cat:"Cursus", src:"NATIONAL" },
  { id:"cu4", q:"[NATIONAL] Quelle est la couleur du moivre pour les établissements d'État ? Pour les privés/catholiques ?", a:"Bleue pour les établissements d'État ; blanche pour les facultés catholiques, écoles ou instituts privés.", cat:"Cursus", src:"NATIONAL" },
  { id:"cu5", q:"[NATIONAL] Que signifie une double palme croisée de lauriers sur le circulaire ?", a:"Un diplôme obtenu (DEUG, DUT, BUT, licence, maîtrise, DU, DE, etc.).", cat:"Cursus", src:"NATIONAL" },
  { id:"cu6", q:"[NATIONAL] Que signifie une tête de vache sur le circulaire ?", a:"Échec aux examens de première session, mais réussite aux rattrapages.", cat:"Cursus", src:"NATIONAL" },
  { id:"cu7", q:"[NATIONAL] Que signifie une tête de mort sur le circulaire ?", a:"Abandon d'une discipline ou réorientation.", cat:"Cursus", src:"NATIONAL" },
  { id:"cu8", q:"[NATIONAL] Comment marque-t-on une année validée par équivalence ?", a:"Par un « e » remplaçant l'étoile.", cat:"Cursus", src:"NATIONAL" },
  { id:"cu9", q:"[NATIONAL] Comment marque-t-on une année en alternance ?", a:"Par un « a » en dessous de l'étoile correspondante.", cat:"Cursus", src:"NATIONAL" },
  { id:"cu10", q:"[NATIONAL] Que place-t-on sous l'étoile d'une année passée à l'étranger ?", a:"Un drapeau du pays.", cat:"Cursus", src:"NATIONAL" },
  { id:"cu11", q:"[NATIONAL] Que symbolise une quille pendant du ruban ?", a:"Le service militaire ou civique effectué à cet endroit du cursus.", cat:"Cursus", src:"NATIONAL" },
  { id:"cu12", q:"[NATIONAL] Que symbolise une abeille sur le circulaire ?", a:"Un cursus exemplaire.", cat:"Cursus", src:"NATIONAL" },
  { id:"cu13", q:"[NATIONAL] Que symbolise un moivre noir disposé de biais sur le circulaire ?", a:"La perte ou le vol de la faluche à l'année correspondante.", cat:"Cursus", src:"NATIONAL" },
  { id:"cu14", q:"[NATIONAL] Comment noter le baccalauréat général sur le circulaire ?", a:"Lettre ɣ (gamma).", cat:"Cursus", src:"NATIONAL" },
  { id:"cu15", q:"[NATIONAL] Comment noter le DAEU sur le circulaire ?", a:"Lettres « DAEU ».", cat:"Cursus", src:"NATIONAL" },
  { id:"cu16", q:"[NATIONAL] Comment note-t-on l'agrégation et/ou le CAPES à la fin du cursus ?", a:"Petit « a » pour l'agrégation et/ou petit « c » pour le CAPES, suivi d'une petite palme.", cat:"Cursus", src:"NATIONAL" },
  { id:"cu17", q:"[NATIONAL] Que signifie une large palme sur le circulaire ?", a:"Major de promotion.", cat:"Cursus", src:"NATIONAL" },
  { id:"cu18", q:"[IPP] Que se passe-t-il en cas de L1 Santé réussie selon le code IPP ?", a:"Tu auras une gomette. En cas de L1 échouée ou en cours, tu n'en auras pas.", cat:"Cursus", src:"IPP" },
  { id:"cu19", q:"[NATIONAL] Que signifie une simple palme à la fin d'un cycle ?", a:"La fin d'un cycle sans diplôme correspondant.", cat:"Cursus", src:"NATIONAL" },

  // ══ INSIGNES PERSONNELS ══
  { id:"ip1", q:"[NATIONAL] Que signifie un chameau à l'endroit ?", a:"Célibataire.", cat:"Insignes perso", src:"NATIONAL" },
  { id:"ip2", q:"[NATIONAL] Que signifie un chameau à l'envers ?", a:"Cœur pris dans l'antichambre du mariage.", cat:"Insignes perso", src:"NATIONAL" },
  { id:"ip3", q:"[IPP] Que signifie un quadripède à bosse à l'endroit selon le code IPP ?", a:"Avoue se masturber.", cat:"Insignes perso", src:"IPP" },
  { id:"ip4", q:"[IPP] Que signifie un quadripède à bosse à l'envers selon le code IPP ?", a:"Ne l'avoue pas.(se masturber)", cat:"Insignes perso", src:"IPP" },
  { id:"ip5", q:"[NATIONAL] Que signifie un cochon à l'endroit ? À l'envers ? (national)", a:"À l'endroit : n'a pas été intégré. À l'envers : a été intégré.", cat:"Insignes perso", src:"NATIONAL" },
  { id:"ip6", q:"[IPP] Que signifie un cochon selon le code IPP ?", a:"Gros porc.", cat:"Insignes perso", src:"IPP" },
  { id:"ip7", q:"[NATIONAL] Que signifie un pendu sur la faluche (national) ?", a:"Marié ou pacsé.", cat:"Insignes perso", src:"NATIONAL" },
  { id:"ip8", q:"[IPP] Que signifie un pendu selon le code IPP ?", a:"Amour de l'alphabet.", cat:"Insignes perso", src:"IPP" },
  { id:"ip9", q:"[NATIONAL] Que signifie un bacchus troué ?", a:"Personne abstème.", cat:"Insignes perso", src:"NATIONAL" },
  { id:"ip10", q:"[NATIONAL] Que signifient les ciseaux en arme personnelle ?", a:"A cousu sa faluche soi-même ou celle de quelqu'un d'autre (intégralement, faluche et rubans, exposant le nombre si envie).", cat:"Insignes perso", src:"NATIONAL" },
  { id:"ip11", q:"[NATIONAL] Que signifie un épi de blé croisé faucille ?", a:"Chanceux aux examens.", cat:"Insignes perso", src:"NATIONAL" },
  { id:"ip12", q:"[IPP] Que signifie une fourchette croisée faucille selon le code IPP ?", a:"S'est rendu compte que ça donne faim d'être communiste.", cat:"Insignes perso", src:"IPP" },
  { id:"ip13", q:"[NATIONAL] Que signifie un épi de blé seul (arme personnelle) ?", a:"Radin.", cat:"Insignes perso", src:"NATIONAL" },
  { id:"ip14", q:"[NATIONAL] Que signifie une feuille de vigne ?", a:"Perte de la virginité dans la vie falucharde.", cat:"Insignes perso", src:"NATIONAL" },
  { id:"ip15", q:"[NATIONAL] Que signifie le sphinx en arme personnelle ?", a:"Polyglotte (langue des signes incluses).", cat:"Insignes perso", src:"NATIONAL" },
  { id:"ip16", q:"[NATIONAL] Que signifie un sabot ?", a:"Breton parti étudier à Paris.", cat:"Insignes perso", src:"NATIONAL" },
  { id:"ip17", q:"[NATIONAL] Que signifie un nounours ?", a:"Gros dormeur.", cat:"Insignes perso", src:"NATIONAL" },
  { id:"ip18", q:"[NATIONAL] Que signifie un épervier ?", a:"Amour des grands espaces.", cat:"Insignes perso", src:"NATIONAL" },
  { id:"ip19", q:"[NATIONAL] Que signifient l'étoile et la foudre en arme personnelle ?", a:"Amour des nouvelles technologies, de l'informatique et/ou des sciences.", cat:"Insignes perso", src:"NATIONAL" },
  { id:"ip20", q:"[IPP] Que signifie une bouteille de chartreuse sur la faluche IPP ?", a:"Est parisien·ne.", cat:"Insignes perso", src:"IPP" },
  { id:"ip21", q:"[IPP] Que signifient les lettres « PUCEAU » sur la faluche IPP ?", a:"Est vierge.", cat:"Insignes perso", src:"IPP" },
  { id:"ip22", q:"[IPP] Que signifie un squelette à l'endroit ? À l'envers ? (IPP)", a:"À l'endroit : personne possédant des os. À l'envers : personne aimant les os.", cat:"Insignes perso", src:"IPP" },
  { id:"ip23", q:"[IPP] Que signifie une chauve-souris à l'envers selon le code IPP ?", a:"Amour de Batman.", cat:"Insignes perso", src:"IPP" },
  { id:"ip24", q:"[IPP] Que signifie une chauve-souris sur crachat selon le code IPP ?", a:"A fait la nouba à la pistoche.", cat:"Insignes perso", src:"IPP" },
  { id:"ip25", q:"[IPP] Que signifient les lettres « KEK » et « TOPKEK » selon le code IPP ?", a:"Personne drôle (par ordre d'intensité : KEK < TOPKEK).", cat:"Insignes perso", src:"IPP" },
  { id:"ip26", q:"[IPP] Que signifient les lettres « XD » à l'endroit et à l'envers selon le code IPP ?", a:"À l'endroit : personne bon public. À l'envers : personne bon public de ses propres blagues.", cat:"Insignes perso", src:"IPP" },
  { id:"ip27", q:"[IPP] Que signifie la lettre « X » seule ? La lettre « D » seule ? (IPP)", a:"X : personne bon public qui ne finit pas ses blagues. D : personne bon public qui ne commence pas ses blagues.", cat:"Insignes perso", src:"IPP" },
  { id:"ip28", q:"[IPP] Que signifie une tête de vache sur la faluche IPP (arme personnelle) ?", a:"Personne moche.", cat:"Insignes perso", src:"IPP" },
  { id:"ip29", q:"[IPP] Que signifie une carotte sur la faluche IPP (arme personnelle) ?", a:"S'est fait·e baiser.", cat:"Insignes perso", src:"IPP" },
  { id:"ip30", q:"[IPP] Que signifie une tête de cheval à l'endroit ? À l'envers ? (IPP)", a:"À l'endroit : a une queue de cheval. À l'envers : galope fort (amour du boum boum).", cat:"Insignes perso", src:"IPP" },
  { id:"ip31", q:"[IPP] Que signifie un pigeon sur la faluche IPP ?", a:"A payé son école 10K.", cat:"Insignes perso", src:"IPP" },
  { id:"ip32", q:"[IPP] Que signifie un sphénoïde sur la faluche IPP (arme personnelle) ?", a:"Chanceux aux examens de la prostate.", cat:"Insignes perso", src:"IPP" },
  { id:"ip33", q:"[IPP] Que signifient les lettres Ko, Mo, Go, To sur la faluche IPP ?", a:"Grande capacité de stockage stomacal (par ordre d'intensité).", cat:"Insignes perso", src:"IPP" },
  { id:"ip34", q:"[IPP] Que signifie un sou troué croisé globe sur la faluche IPP ?", a:"Cataphile.", cat:"Insignes perso", src:"IPP" },
  { id:"ip35", q:"[IPP] Que signifie une harpe sur la faluche IPP ?", a:"Amour de la Guinness.", cat:"Insignes perso", src:"IPP" },
  { id:"ip36", q:"[IPP] Que signifie une abeille sur ruban violet selon le code IPP ?", a:"Myope.", cat:"Insignes perso", src:"IPP" },
  { id:"ip37", q:"[IPP] Que signifie « hache croisé carotte » sur la faluche IPP ?", a:"Affaire de famille.", cat:"Insignes perso", src:"IPP" },
  { id:"ip38", q:"[IPP] Que signifie un globe sur satin vert selon le code IPP ?", a:"N'est pas étudiant.", cat:"Insignes perso", src:"IPP" },
  { id:"ip39", q:"[IPP] Que signifie un lion sur la faluche IPP ?", a:"Amour du Roi Lion.", cat:"Insignes perso", src:"IPP" },
  { id:"ip40", q:"[IPP] Que signifie une fourchette (à 2 pics) sur la faluche IPP ?", a:"Forklift certified.", cat:"Insignes perso", src:"IPP" },
  { id:"ip41", q:"[IPP] Que signifie une tomate sur la faluche IPP ?", a:"Mange 5 fruits et légumes par jour.", cat:"Insignes perso", src:"IPP" },
  { id:"ip42", q:"[IPP] Que signifie un pachy (pachyderme) selon le code IPP (arme personnelle) ?", a:"Humour ingénieur.", cat:"Insignes perso", src:"IPP" },

  // ══ INSIGNES PARTENAIRE ══
  { id:"part1", q:"[NATIONAL] Quels sont les insignes décernés par le/la partenaire (national) et que signifient-ils ?", a:"Épée ou pensée (selon identité de genre) : fin baiseur. Flèche : éjaculateur précoce. Lime : acte laborieux et difficile.", cat:"Insignes partenaire", src:"NATIONAL" },
  { id:"part2", q:"[IPP] Quels sont les insignes décernés par lea/les partenaires selon le code IPP ?", a:"Pensée : a réalisé la plus grande partie. Flèche : a fini sa partie lea premier·e. Lime : a galéré sa mère.", cat:"Insignes partenaire", src:"IPP" },

  // ══ INSIGNES GM ══
  { id:"gm1", q:"[NATIONAL] Que signifient les anneaux olympiques décernés par un GM ?", a:"Excellence sportive universitaire (après compétitions régionales ou nationales).", cat:"Insignes GM", src:"NATIONAL" },
  { id:"gm2", q:"[IPP] Que signifient les anneaux olympiques selon le code IPP ?", a:"STAPS qui a réussi.", cat:"Insignes GM", src:"IPP" },
  { id:"gm3", q:"[NATIONAL] Que signifie le Bacchus décerné par un GM (national) ?", a:"Dignité dans l'ivresse (retournable et retirable).", cat:"Insignes GM", src:"NATIONAL" },
  { id:"gm4", q:"[IPP] Que signifie le Bacchus selon le code IPP ?", a:"N'a pas perdu son sac à main/grosse trousse.", cat:"Insignes GM", src:"IPP" },
  { id:"gm5", q:"[NATIONAL] Que signifie une bouteille de Bordeaux (national) ?", a:"Cuite certifiée — blâme si la cuite a engendré un danger. Coefficient multiplicateur si récidive.", cat:"Insignes GM", src:"NATIONAL" },
  { id:"gm6", q:"[IPP] Que signifie une bouteille de Bordeaux selon le code IPP ?", a:"Invitation officielle des croix à se la coller sévère.", cat:"Insignes GM", src:"IPP" },
  { id:"gm7", q:"[NATIONAL] Que signifie une bouteille de champagne décernée par un GM ?", a:"Coma éthylique certifié.", cat:"Insignes GM", src:"NATIONAL" },
  { id:"gm8", q:"[IPP] Que signifie une bouteille de champagne selon le code IPP ?", a:"Quand l'invitation (bouteille de Bordeaux) est partie en live.", cat:"Insignes GM", src:"IPP" },
  { id:"gm9", q:"[NATIONAL] Que signifie un coq décerné par un GM (national) ?", a:"Grande gueule sachant l'ouvrir.", cat:"Insignes GM", src:"NATIONAL" },
  { id:"gm10", q:"[IPP] Que signifie un coq selon le code IPP ?", a:"Grande gueule sucant des bites.", cat:"Insignes GM", src:"IPP" },
  { id:"gm11", q:"[NATIONAL] Que signifie un cor de chasse décerné par un GM (national) ?", a:"Grand charmeur devant l'éternel.", cat:"Insignes GM", src:"NATIONAL" },
  { id:"gm12", q:"[IPP] Que signifie un cor de chasse selon le code IPP ?", a:"Try hard.", cat:"Insignes GM", src:"IPP" },
  { id:"gm13", q:"[NATIONAL] Que signifie un entonnoir décerné par un GM (national) ?", a:"Personne abstème par décision des croix (période d'abstinence imposée).", cat:"Insignes GM", src:"NATIONAL" },
  { id:"gm14", q:"[IPP] Que signifie un entonnoir selon le code IPP ?", a:"Garage à fillot.", cat:"Insignes GM", src:"IPP" },
  { id:"gm15", q:"[NATIONAL] Que signifie une fourchette sur ruban bleu ?", a:"Cordon bleu — décerné après dégustation d'un repas complet préparé par le faluchard.", cat:"Insignes GM", src:"NATIONAL" },
  { id:"gm16", q:"[NATIONAL] Que signifie une hache (insigne GM) ?", a:"Prise de guerre — emprunt à court terme d'un objet d'une communauté de ville, exceptionnel et sans vandalisme.", cat:"Insignes GM", src:"NATIONAL" },
  { id:"gm17", q:"[NATIONAL] Que signifie un pachyderme décerné par un GM ?", a:"Personne lourde.", cat:"Insignes GM", src:"NATIONAL" },
  { id:"gm18", q:"[NATIONAL] Que signifie un parapluie ouvert ? Un parapluie fermé ? (national)", a:"Ouvert : a vomi dans sa faluche. Fermé : a vomi dans sa faluche et l'a remise sur sa tête.", cat:"Insignes GM", src:"NATIONAL" },
  { id:"gm19", q:"[NATIONAL] Que signifie une poule décernée par un GM (national) ?", a:"Personne très chaude.", cat:"Insignes GM", src:"NATIONAL" },
  { id:"gm20", q:"[IPP] Que signifie une poule selon le code IPP ? Et une poule à l'envers ?", a:"Poule : personne bien. Poule à l'envers : Tchoin mais inclusif tqt.", cat:"Insignes GM", src:"IPP" },
  { id:"gm21", q:"[NATIONAL] Que signifie un singe décerné par un GM (national) ?", a:"Quémandeur d'insigne (empêche de recevoir tout autre insigne).", cat:"Insignes GM", src:"NATIONAL" },
  { id:"gm22", q:"[IPP] Que signifie un singe selon le code IPP ?", a:"Connerie certifiée.", cat:"Insignes GM", src:"IPP" },
  { id:"gm23", q:"[NATIONAL] Que signifie un sou troué (national, insigne GM) ?", a:"Nuit passée au poste de police pour motif étudiant (sans condamnation).", cat:"Insignes GM", src:"NATIONAL" },
  { id:"gm24", q:"[IPP] Que signifie un sou troué selon le code IPP (insigne des croix) ?", a:"Pauvre de ouf.", cat:"Insignes GM", src:"IPP" },
  { id:"gm25", q:"[NATIONAL] Que signifie une tortue décernée par un GM ?", a:"Grand hébergeur.", cat:"Insignes GM", src:"NATIONAL" },
  { id:"gm26", q:"[NATIONAL] Que signifie un volant décerné par un GM ?", a:"Conducteur de fin de soirée (sobriété absolue obligatoire).", cat:"Insignes GM", src:"NATIONAL" },
  { id:"gm27", q:"[NATIONAL] Que signifie une clé de sol et comment est-elle décernée ?", a:"Digne chanteur de paillardes. Décernée avec répertoire de 5 à 10 chansons chantées dans un ordre aléatoire.", cat:"Insignes GM", src:"NATIONAL" },
  { id:"gm28", q:"[NATIONAL] Que signifie un mammouth (national) et comment est-il décerné ?", a:"Gardien des traditions. Décerné après questionnaire approfondi + preuve de transmission. Rare : 1-2 par ville.", cat:"Insignes GM", src:"NATIONAL" },
  { id:"gm29", q:"[IPP] Que signifie un mammouth selon le code IPP ?", a:"Fait partie des meubles.", cat:"Insignes GM", src:"IPP" },
  { id:"gm30", q:"[IPP] Que signifie une chouette décernée par les croix IPP ?", a:"Personne chouette, tellement chouette que si elle se l'auto-décerne, c'est pas très grave.", cat:"Insignes GM", src:"IPP" },
  { id:"gm31", q:"[IPP] Que signifie un dauphin selon le code IPP ?", a:"Est un animal.", cat:"Insignes GM", src:"IPP" },
  { id:"gm32", q:"[IPP] Que signifie un clou décerné par les croix IPP ?", a:"S'est fait décerner un clou.", cat:"Insignes GM", src:"IPP" },
  { id:"gm33", q:"[IPP] Que signifie une épée décernée par les croix IPP ?", a:"S'est masturbé 8 fois en 24 heures.", cat:"Insignes GM", src:"IPP" },
  { id:"gm34", q:"[IPP] Que signifie « BIFLE sur ruban bleu noir liseré doré » selon le code IPP ?", a:"A raté son élection de croix.", cat:"Insignes GM", src:"IPP" },

  // ══ INSIGNES RÉGIONAUX ══
  { id:"ir1", q:"[NATIONAL] Insigne régional : Berry", a:"Âne", cat:"Insignes régionaux", src:"NATIONAL" },
  { id:"ir2", q:"[NATIONAL] Insigne régional : Provence", a:"Cigale", cat:"Insignes régionaux", src:"NATIONAL" },
  { id:"ir3", q:"[NATIONAL] Insigne régional : Alsace", a:"Cigogne", cat:"Insignes régionaux", src:"NATIONAL" },
  { id:"ir4", q:"[NATIONAL] Insigne régional : Lorraine", a:"Chardon", cat:"Insignes régionaux", src:"NATIONAL" },
  { id:"ir5", q:"[NATIONAL] Insigne régional : Camargue", a:"Croix Camarguaise", cat:"Insignes régionaux", src:"NATIONAL" },
  { id:"ir6", q:"[NATIONAL] Insigne régional : Occitanie", a:"Croix Occitane", cat:"Insignes régionaux", src:"NATIONAL" },
  { id:"ir7", q:"[NATIONAL] Insigne régional : Savoie", a:"Edelweiss (ajouté au 137e anniversaire)", cat:"Insignes régionaux", src:"NATIONAL" },
  { id:"ir8", q:"[NATIONAL] Insigne régional : Limousin", a:"Houe", cat:"Insignes régionaux", src:"NATIONAL" },
  { id:"ir9", q:"[NATIONAL] Insigne régional : Pays Basque", a:"Lauburu", cat:"Insignes régionaux", src:"NATIONAL" },
  { id:"ir10", q:"[NATIONAL] Insigne régional : Lyon", a:"Lion dressé", cat:"Insignes régionaux", src:"NATIONAL" },
  { id:"ir11", q:"[NATIONAL] Insigne régional : Normandie", a:"Lion passant", cat:"Insignes régionaux", src:"NATIONAL" },
  { id:"ir12", q:"[NATIONAL] Insigne régional : Bretagne", a:"Hermine (ou pic d'hermine)", cat:"Insignes régionaux", src:"NATIONAL" },
  { id:"ir13", q:"[NATIONAL] Insigne régional : Vendée", a:"Sacré Cœur Vendéen", cat:"Insignes régionaux", src:"NATIONAL" },
  { id:"ir14", q:"[NATIONAL] Insigne régional : Ardennes", a:"Sanglier", cat:"Insignes régionaux", src:"NATIONAL" },
  { id:"ir15", q:"[NATIONAL] Insigne régional : Catalogne", a:"Soulier Catalan", cat:"Insignes régionaux", src:"NATIONAL" },
  { id:"ir16", q:"[NATIONAL] Insigne régional : Bourgogne", a:"Taste-vin", cat:"Insignes régionaux", src:"NATIONAL" },
  { id:"ir17", q:"[NATIONAL] Insigne régional : Corse", a:"Tête de Maure", cat:"Insignes régionaux", src:"NATIONAL" },

  // ══ VELOURS / RUBANS ══
  { id:"v1", q:"[NATIONAL] Que place-t-on lors du décès d'un patient durant une garde d'un étudiant en santé ?", a:"Une unique faux placée sur le velours noir.", cat:"Velours/Rubans", src:"NATIONAL" },
  { id:"v2", q:"[NATIONAL] Où se place la devise et dans quelles langues ?", a:"Sur le velours du frontal à l'occipital, à gauche du ruban de province natale. En grec, latin, français, hébreu, langue régionale, patois, etc.", cat:"Velours/Rubans", src:"NATIONAL" },
  { id:"v3", q:"[NATIONAL] De quelle couleur est le ruban des élus étudiants (conseil d'UFR, université, etc.) ?", a:"Ruban jaune, du frontal à l'occipital, extrémité occipitale libre (pendentif).", cat:"Velours/Rubans", src:"NATIONAL" },
  { id:"v4", q:"[NATIONAL] Insigne + ruban : élu au conseil d'UFR", a:"Grenouille argentée — sur ruban jaune pendentif.", cat:"Velours/Rubans", src:"NATIONAL" },
  { id:"v5", q:"[NATIONAL] Insigne + ruban : élu au conseil d'université", a:"Grenouille dorée — sur ruban jaune pendentif.", cat:"Velours/Rubans", src:"NATIONAL" },
  { id:"v6", q:"[NATIONAL] Insigne + ruban : élu au CROUS", a:"Tortue argentée — sur ruban jaune pendentif.", cat:"Velours/Rubans", src:"NATIONAL" },
  { id:"v7", q:"[NATIONAL] Insigne + ruban : élu au CNOUS", a:"Tortue dorée — sur ruban jaune pendentif.", cat:"Velours/Rubans", src:"NATIONAL" },
  { id:"v8", q:"[NATIONAL] Insigne + ruban : VPE d'université", a:"Étoile dorée — sur ruban jaune pendentif.", cat:"Velours/Rubans", src:"NATIONAL" },
  { id:"v9", q:"[NATIONAL] Insigne + ruban : VPE CROUS", a:"Étoile dorée — sur ruban rouge (pendentif jaune).", cat:"Velours/Rubans", src:"NATIONAL" },
  { id:"v10", q:"[NATIONAL] Insigne + ruban : VPE d'UFR ou CA hors université", a:"Étoile argentée — sur ruban jaune pendentif.", cat:"Velours/Rubans", src:"NATIONAL" },
  { id:"v11", q:"[NATIONAL] Insigne + ruban : élu au conseil disciplinaire", a:"Glaive et Balance — sur ruban jaune pendentif.", cat:"Velours/Rubans", src:"NATIONAL" },
  { id:"v12", q:"[IPP] Quel insigne unique pour mandat de délégué·e mutualiste selon le code IPP ?", a:"Une étoile dorée par mandat, sur un petit ruban bleu.", cat:"Velours/Rubans", src:"IPP" },
  { id:"v13", q:"[NATIONAL] Quels rubans portent les membres du bureau d'une association nationale ? Le président ?", a:"Membres du bureau : ruban tricolore avec un filet blanc de chaque côté. Président : ruban tricolore avec une bande blanche de chaque côté.", cat:"Velours/Rubans", src:"NATIONAL" },
  { id:"v14", q:"[NATIONAL] Quel ruban porte un élu au plan européen ? Au plan international ?", a:"Européen : couleurs de l'Europe. International : couleurs de l'ONU.", cat:"Velours/Rubans", src:"NATIONAL" },

  // ══ TYPES DE FALUCHES ══
  { id:"tf1", q:"[NATIONAL] Combien de types de faluches existe-t-il et par quoi se distinguent-ils ?", a:"Six types, distingués par leurs confections (circulaires, velours) ou l'organisation du velours — pas par leurs coutures.", cat:"Types de faluche", src:"NATIONAL" },
  { id:"tf2", q:"[NATIONAL] Comment se distingue la faluche alsacienne ?", a:"Par un ruban de circulaire maintenu par six passants.", cat:"Types de faluche", src:"NATIONAL" },
  { id:"tf3", q:"[NATIONAL] Quelles sont les 4 interprétations des six passants de la faluche alsacienne ?", a:"Les 6 côtés d'un bock de bière ; les 6 cépages d'Alsace ; les 6 régions d'Alsace ; les barreaux d'une prison lors de l'occupation allemande.", cat:"Types de faluche", src:"NATIONAL" },
  { id:"tf4", q:"[NATIONAL] Comment se distingue la faluche lilloise ?", a:"Aussi appelée « faluche nationale », la plus couramment utilisée. Circulaire rigide, renforcé par du plastique et gainé de cuir.", cat:"Types de faluche", src:"NATIONAL" },
  { id:"tf5", q:"[NATIONAL] Comment se distingue la faluche marseillaise ?", a:"Velours beaucoup plus large par rapport à la faluche nationale.", cat:"Types de faluche", src:"NATIONAL" },
  { id:"tf6", q:"[NATIONAL] Comment se distingue la faluche montpelliéraine ?", a:"Velours plus large et 4 crevés en satin aux couleurs de la discipline, reliés par un bouton au centre. Réservée aux étudiants de l'Université de Montpellier.", cat:"Types de faluche", src:"NATIONAL" },
  { id:"tf7", q:"[NATIONAL] Quelles sont les couleurs des crevés de la faluche montpelliéraine pour chaque discipline médicale ?", a:"Médecine : 4 bordeaux. Pharmacie : 4 verts. Chirurgie dentaire : 2 bordeaux + 2 violets. Paramédical : 4 roses.", cat:"Types de faluche", src:"NATIONAL" },
  { id:"tf8", q:"[NATIONAL] Quelles sont les 3 raisons des crevés montpelliérains ?", a:"1. Montpellier = plus ancienne université de France (fin XIIe s.). 2. Toque à quatre cornes dès la création. 3. Hommage à François Rabelais, étudiant en médecine à partir de 1530.", cat:"Types de faluche", src:"NATIONAL" },
  { id:"tf9", q:"[NATIONAL] Comment se distingue la faluche perpignanaise ?", a:"Ruban de circulaire maintenu par cinq passants.", cat:"Types de faluche", src:"NATIONAL" },
  { id:"tf10", q:"[NATIONAL] Comment se distingue la faluche tourangelle ?", a:"Circulaire souple (opposé de la lilloise). Portée notamment par les membres de l'Ordre du Vénéré Bitard.", cat:"Types de faluche", src:"NATIONAL" },

  // ══ POTAGER ══
  { id:"pot1", q:"[NATIONAL] Que place-t-on dans le potager pour un rapport sexuel classique ?", a:"Une carotte.", cat:"Potager", src:"NATIONAL" },
  { id:"pot2", q:"[NATIONAL] Que place-t-on dans le potager pour une fellation ?", a:"Un poireau.", cat:"Potager", src:"NATIONAL" },
  { id:"pot3", q:"[NATIONAL] Que place-t-on dans le potager pour une sodomie ?", a:"Un navet.", cat:"Potager", src:"NATIONAL" },
  { id:"pot4", q:"[NATIONAL] Que place-t-on dans le potager pour un cunnilingus ?", a:"Une betterave.", cat:"Potager", src:"NATIONAL" },
  { id:"pot5", q:"[NATIONAL] Quelle règle s'applique en cas de dépucelage dans le potager ?", a:"On place deux légumes en X.", cat:"Potager", src:"NATIONAL" },
  { id:"pot6", q:"[NATIONAL] Que se passe-t-il si un insigne du potager est noirci ?", a:"Exhibition notable → gel du potager.", cat:"Potager", src:"NATIONAL" },
  { id:"pot7", q:"[NATIONAL] Un couple officiel peut-il recevoir des insignes de potager ?", a:"Non.", cat:"Potager", src:"NATIONAL" },
  { id:"pot8", q:"[NATIONAL] Quelle règle de sécurité s'applique au potager ?", a:"« Pas de capote, pas de carotte » : toute pénétration doit être protégée.", cat:"Potager", src:"NATIONAL" },

  // ══ GM & GC ══
  { id:"gmgc1", q:"[NATIONAL] Quelle est la distinction du Grand Maître (GM) ?", a:"Croix au mérite émaillée de blanc, soutenue par un ruban aux couleurs et matière de la discipline ou ville du mandat, pendant à gauche de la faluche.", cat:"GM & GC", src:"NATIONAL" },
  { id:"gmgc2", q:"[IPP] Quelle est la distinction du GM selon le code IPP ?", a:"Croix du mérite émaillée de blanc soutenue par un ruban bleu et noir.", cat:"GM & GC", src:"IPP" },
  { id:"gmgc3", q:"[NATIONAL] Quelle est la distinction du Grand Chambellan (GC) ?", a:"Croix au mérite non émaillée, soutenue par un ruban à la couleur et matière de la discipline ou ville du mandat.", cat:"GM & GC", src:"NATIONAL" },
  { id:"gmgc4", q:"[NATIONAL] Quelle distinction porte un ancien GM une fois son mandat terminé ?", a:"Le ruban de rappel (couleur de la filière) à droite, orné d'un soleil.", cat:"GM & GC", src:"NATIONAL" },
  { id:"gmgc5", q:"[NATIONAL] Quelle distinction porte un ancien GC une fois son mandat terminé ?", a:"Le ruban de rappel (couleur de la filière) à droite, orné d'une lune.", cat:"GM & GC", src:"NATIONAL" },
  { id:"gmgc6", q:"[NATIONAL] Qui peut prétendre au titre de GM ? Quelles exceptions ?", a:"N'importe quel faluchard, sauf : honoris causa, étudiants par correspondance, faluchards avec blâmes. Déconseillé avant le statut d'ancien.", cat:"GM & GC", src:"NATIONAL" },
  { id:"gmgc7", q:"[NATIONAL] Pour quelle durée maximum un GM peut-il exercer ?", a:"Un ou deux ans maximum.", cat:"GM & GC", src:"NATIONAL" },
  { id:"gmgc8", q:"[NATIONAL] Dans quel délai le GM doit-il organiser les baptêmes ?", a:"Entre 4 et 6 mois maximum après déclaration des impétrants.", cat:"GM & GC", src:"NATIONAL" },
  { id:"gmgc9", q:"[NATIONAL] Le défaluchage avec prise de la faluche est-il légal ?", a:"Non, il est illégal.", cat:"GM & GC", src:"NATIONAL" },
  { id:"gmgc10", q:"[IPP] Quel est le rôle principal du GC selon le code IPP ?", a:"Se doit de servir les verres à la perfection.", cat:"GM & GC", src:"IPP" },
  { id:"gmgc11", q:"[IPP] Qu'est-ce que le prophète de la filière IPP et quelle est sa distinction (Article XI) ?", a:"Un prophète distingué par une tête de mort sur feuille de vigne, qui veille à la philosophie IPP et peut sanctionner les écarts par une tête de mort sur étoile et foutre.", cat:"GM & GC", src:"IPP" },
  { id:"gmgc12", q:"[NATIONAL] Par quoi un GM peut-il se faire remplacer pour officier un baptême ?", a:"Par un GC (s'il en a), ou par trois anciens désignés.", cat:"GM & GC", src:"NATIONAL" },

  // ══ BAPTÊME ══
  { id:"b1", q:"[NATIONAL] Par qui doit être baptisée toute faluche ?", a:"Par un Grand Maître (ou un représentant légitime) de la filière ou de la ville, sous l'œil attentif des anciens.", cat:"Baptême", src:"NATIONAL" },
  { id:"b2", q:"[NATIONAL] Que risque un étudiant surpris à baptiser sans porter de faluche ?", a:"Il est lui-même considéré comme impétrant et encourt les pires sévices.", cat:"Baptême", src:"NATIONAL" },

  // ══ PARRAINS / MARRAINES ══
  { id:"pm1", q:"[NATIONAL] Un parrain/marraine doit-il boire beaucoup lors du baptême de son filleul ?", a:"Non, il doit boire peu et peut boire pour lui afin que le filleul se souvienne de son baptême et de son serment.", cat:"Parrains", src:"NATIONAL" },
  { id:"pm2", q:"[NATIONAL] Que doit garder le parrain/marraine à l'issue du baptême ?", a:"La bouteille de champagne et son bouchon (à attacher à l'arrière de la faluche).", cat:"Parrains", src:"NATIONAL" },
  { id:"pm3", q:"[NATIONAL] Qui doit trouver le surnom du filleul ?", a:"Le parrain ou la marraine (drôle, collant à la peau, et apprécié par le filleul).", cat:"Parrains", src:"NATIONAL" },

  // ══ HONORIS CAUSA ══
  { id:"hc1", q:"[NATIONAL] Que signifie « Honoris Causa » ?", a:"« La cause par l'honneur ».", cat:"Honoris Causa", src:"NATIONAL" },
  { id:"hc2", q:"[NATIONAL] Un Honoris Causa peut-il avoir des parrains ou des fillots ?", a:"Non (décision du 125e anniversaire).", cat:"Honoris Causa", src:"NATIONAL" },
  { id:"hc3", q:"[NATIONAL] Comment se distingue une faluche Honoris Causa non baptisée ?", a:"Par l'absence de bouchon à l'occipital.", cat:"Honoris Causa", src:"NATIONAL" },
  { id:"hc4", q:"[NATIONAL] Quelles couleurs de velours avaient les anciennes faluches Honoris Causa ?", a:"Amarante, bordeaux, orange (médecine Montpellier) ou blanche (médecine Nîmes). Actuellement souvent velours noir.", cat:"Honoris Causa", src:"NATIONAL" },

  // ══ GRANDS SINGES ══
  { id:"gs1", q:"[NATIONAL] Quel est le nombre fixe de membres du Conseil des Grands Singes ?", a:"13 membres.", cat:"Grands Singes", src:"NATIONAL" },
  { id:"gs2", q:"[NATIONAL] Comment est élu un membre du Conseil des Grands Singes ?", a:"Par les autres membres ; le nom doit être proposé par un tiers. Toute demande directe annule la candidature.", cat:"Grands Singes", src:"NATIONAL" },
  { id:"gs3", q:"[NATIONAL] Quel est l'insigne d'un Grand Singe et sur quel ruban ?", a:"Un singe sur un ruban crème, avec le chiffre de l'anniversaire correspondant à son élection.", cat:"Grands Singes", src:"NATIONAL" },
  { id:"gs4", q:"[NATIONAL] Pour quelles raisons un Grand Singe peut-il être destitué ?", a:"Inactivité sur 18 mois consécutifs ; manque de respect des traditions estudiantines ; abus de pouvoirs.", cat:"Grands Singes", src:"NATIONAL" },
  { id:"gs5", q:"[NATIONAL] Lors de quel congrès le Conseil des Grands Singes a-t-il été créé ?", a:"Lors du 106e anniversaire à Toulouse (1994).", cat:"Grands Singes", src:"NATIONAL" },

  // ══ ARCHIVISTES ══
  { id:"arch1", q:"[NATIONAL] Lors de quel anniversaire le Groupement des Archivistes a-t-il été officialisé ?", a:"Lors du 131e anniversaire.", cat:"Archivistes", src:"NATIONAL" },
  { id:"arch2", q:"[NATIONAL] Les archivistes reçoivent-ils un insigne ou un ruban ?", a:"Aucun — travail volontaire, sans glorification personnelle.", cat:"Archivistes", src:"NATIONAL" },
  { id:"arch3", q:"[NATIONAL] Quel est le but principal du Groupement des Archivistes ?", a:"Centraliser et sécuriser les informations du folklore faluchard pour limiter la propagation de légendes urbaines, faux insignes ou particularités erronées.", cat:"Archivistes", src:"NATIONAL" },

  { id:"cv19", q:"[NATIONAL] Circulaire complet : PASS", a:"Circulaire couleur de la filière santé choisie (variable) pour PASS — insigne : Tête de mort sur fémurs croisés", cat:"Circulaire velours", src:"NATIONAL" },
  { id:"cv20", q:"[NATIONAL] Circulaire complet : LAS", a:"Circulaire couleur de la discipline majoritaire (variable) pour LAS — insigne : emblème de la discipline majoritaire", cat:"Circulaire velours", src:"NATIONAL" },
  { id:"cs32", q:"[NATIONAL] Circulaire complet : IUP", a:"Satin couleurs de la discipline étudiée (variable) pour IUP — insigne : Lettres « IUP »", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs33", q:"[NATIONAL] Circulaire complet : Écoles nationales", a:"Satin couleurs du pays de l'école (variable) pour Écoles nationales — insigne : Lettres des initiales de l'école", cat:"Circulaire satin", src:"NATIONAL" },
  { id:"cs34", q:"[NATIONAL] Circulaire complet : Communication", a:"Satin couleurs de la filière de rattachement (variable) pour Communication — insigne : Caducée de Mercure", cat:"Circulaire satin", src:"NATIONAL" },

];
